export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";


export const LOAD_INDIVIDUALS = "LOAD_INDIVIDUALS";
export const CREATE_INDIVIDUAL = "CREATE_INDIVIDUAL";
export const UPLOAD_INDIVIDUAL = "UPLOAD_INDIVIDUAL";

export const LOAD_MEDIA = "LOAD_MEDIA";
export const CREATE_MEDIA_COLLECTION = "CREATE_MEDIA_COLLECTION";
export const UPLOAD_MEDIA = "UPLOAD_MEDIA";

export const SUCCESS = "SUCCESS";
export const FAILURE = "FAILURE";
export const CLEAR = "CLEAR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const LOAD_USERS_REQUEST = "LOAD_USERS_REQUEST";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_FAILURE = "LOAD_USERS_FAILURE";

export const FIELD_VALUE_INVALID = "FIELD_VALUE_INVALID";

export const LOAD_NAV_REQUEST = "LOAD_NAV_REQUEST";
export const LOAD_NAV_SUCCESS = "LOAD_NAV_SUCCESS";
export const LOAD_NAV_FAILURE = "LOAD_NAV_FAILURE";
export const EXPAND_COLLAPSE_NAV_ITEM = "EXPAND_COLLAPSE_NAV_ITEM";

export const FETCH_CONTEXT_REQUEST = "FETCH_CONTEXT_REQUEST";
export const FETCH_CONTEXT_SUCCESS = "FETCH_CONTEXT_SUCCESS";
export const FETCH_CONTEXT_FAILURE = "FETCH_CONTEXT_FAILURE";

export const GET_WATCHLISTS_SUCCESS = "GET_WATCHLISTS_SUCCESS";
export const GET_WATCHLISTS_FAILURE = "GET_WATCHLISTS_FAILURE";
export const GET_WATCHLISTS_REQUEST = "GET_WATCHLISTS_REQUEST";

export const FETCH_MEDIA_REQUEST = "FETCH_MEDIA_REQUEST";
export const FETCH_MEDIA_SUCCESS = "FETCH_MEDIA_SUCCESS";
export const FETCH_MEDIA_FAILURE = "FETCH_MEDIA_FAILURE";

export const DELETE_MEDIA_REQUEST = "DELETE_MEDIA_REQUEST";
export const DELETE_MEDIA_SUCCESS = "DELETE_MEDIA_SUCCESS";
export const DELETE_MEDIA_FAILURE = "DELETE_MEDIA_FAILURE";


export const ADD_BREADCRUMB_ITEM = "ADD_BREADCRUMB_ITEM";
export const REMOVE_BREADCRUMB_ITEM = "REMOVE_BREADCRUMB_ITEM";
export const SET_BREADCRUMB = "SET_BREADCRUMB";

export const FETCH_PROCESSING_STATUS_REQUEST = "FETCH_PROCESSING_STATUS_REQUEST";
export const FETCH_PROCESSING_STATUS_SUCCESS = "FETCH_PROCESSING_STATUS_SUCCESS";
export const FETCH_PROCESSING_STATUS_FAILURE = "FETCH_PROCESSING_STATUS_FAILURE";

export const OPEN_DIALOG = "OPEN_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";

export const GET_SETTINGS_REQUEST = "GET_SETTINGS_REQUEST";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAILURE = "GET_SETTINGS_FAILURE";
export const SETTING_CHANGED = "SETTING_CHANGED";
export const SETTING_SELECTED = "SETTING_SELECTED";
export const SETTING_DESELECTED = "SETTING_DESELECTED";

export const GET_SETTINGS_CATEGORIES_REQUEST = "GET_SETTINGS_CATEGORIES_REQUEST";
export const GET_SETTINGS_CATEGORIES_SUCCESS = "GET_SETTINGS_CATEGORIES_SUCCESS";
export const GET_SETTINGS_CATEGORIES_FAILURE = "GET_SETTINGS_CATEGORIES_FAILURE";
export const SETTING_CATEGORY_CHANGED = "SETTING_CATEGORY_CHANGED";
export const SETTING_CATEGORY_SELECTED = "SETTING_CATEGORY_SELECTED";
export const SETTING_CATEGORY_DESELECTED = "SETTING_CATEGORY_DESELECTED";
