export const settingConstants = {
    GET_SETTINGS_SUCCESS: 'GET_SETTINGS_SUCCESS',
    GET_SETTINGS_FAILURE: 'GET_SETTINGS_FAILURE',
    GET_SETTINGS_CATEGORIES_SUCCESS: 'GET_SETTINGS_CATEGORIES_SUCCESS',
    GET_SETTINGS_CATEGORIES_FAILURE: 'GET_SETTINGS_CATEGORIES_FAILURE',
    SETTING_CHANGED: 'SETTING_CHANGED',
    SETTING_CATEGORY_CHANGED: 'SETTING_CATEGORY_CHANGED',
    SETTING_SELECTED: 'SETTING_SELECTED',
    SETTING_DESELECTED: 'SETTING_DESELECTED',
    SETTING_CATEGORY_SELECTED: 'SETTING_CATEGORY_SELECTED',
    SETTING_CATEGORY_DESELECTED: 'SETTING_CATEGORY_DESELECTED',
    SETTINGS_SAVED_SUCCESSFULLY: 'SETTINGS_SAVED_SUCCESSFULLY',
    GET_DETECTORS_SUCCESS: 'GET_DETECTORS_SUCCESS',
    DETECTOR_CHANGED_SUCCESS: 'DETECTOR_CHANGED_SUCCESS'
}
