export const settingConstants = {
    GET_SETTINGS_SUCCESS: 'GET_SETTINGS_SUCCESS',
    GET_SETTINGS_FAILURE: 'GET_SETTINGS_FAILURE',
    GET_SETTINGS_CATEGORIES_SUCCESS: 'GET_SETTINGS_CATEGORIES_SUCCESS',
    GET_SETTINGS_CATEGORIES_FAILURE: 'GET_SETTINGS_CATEGORIES_FAILURE'
}
